---
title: "Wine Analysis"
author: "Nick Howard"
date: "May 7, 2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}


wt<- wine.training.data

names(wt)

library(psych)

write.table((describe(wt)), "summmarystatsforwine variables.csv", sep = ",")

colSums(is.na(wt))

write.table(colSums(is.na(wt)), "nawine.csv", sep = ",")

colSums(wt=="")

write.table(colSums(wt==""), "blankwine.csv", sep = ",")

colSums(wt==" ")

write.table(colSums(wt==" "), "blankwine2.csv", sep = ",")


write.table((summary(wt)), "summmarystatsforwine variables2.csv", sep = ",")

table(wt$TARGET)

A<-c(2374,244,1091,2611,3177,2014,765,142,17)
B<-c("0","1","2","3","4","5","6","7","8")

barplot(A,names.arg=B,xlab="Cases",ylab="Count",col="black",
        main="Cases of wine purchased after testing",cex.axis=.6, cex.main=1, cex.sub=1, cex.names = .6)

mintar<- subset(wt,wt$TARGET=="0")
medtar<- subset(wt,wt$TARGET=="3")
maxtar<- subset(wt,wt$TARGET=="8")

library(ggplot2)

qplot(mintar$STARS,
      binwidth = 0.5,  
      main = "Stars of wine with 0 cases sold", 
      xlab = "Age",  
      fill=I("black"))

qplot(medtar$STARS,
      binwidth = 0.5,  
      main = "Stars of wine with 3 cases sold", 
      xlab = "Age",  
      fill=I("black"))

qplot(maxtar$STARS,
      binwidth = 0.5,  
      main = "Stars of wine with 8 cases sold", 
      xlab = "Age",  
      fill=I("black"))

ggplot(wt, aes(x=wt$FixedAcidity, y=wt$TARGET)) +
    geom_point(shape=1) +
    geom_smooth(method=lm) 


ggplot(wt, aes(x=wt$STARS, y=wt$FixedAcidity)) +
    geom_point(shape=1) 

ggplot(wt, aes(x=wt$TARGET, y=wt$FixedAcidity)) +
    geom_point(shape=1) 

qplot(wt$FixedAcidity,
      binwidth = 1,  
      main = "Fixed Acidity", 
      xlab = "stars",  
      fill=I("black"))

ggplot(wt, aes(x=wt$STARS, y=wt$VolatileAcidity)) +
    geom_point(shape=1) 

ggplot(wt, aes(x=wt$TARGET, y=wt$VolatileAcidity)) +
    geom_point(shape=1) 

qplot(wt$VolatileAcidity,
      binwidth = 1,  
      main = "Fixed Acidity", 
      xlab = "stars",  
      fill=I("black"))

ggplot(wt, aes(x=wt$STARS, y=wt$CitricAcid)) +
    geom_point(shape=1) 

ggplot(wt, aes(x=wt$TARGET, y=wt$CitricAcid)) +
    geom_point(shape=1) 

qplot(wt$CitricAcid,
      binwidth = 1, 
      fill=I("black"))

ggplot(wt, aes(x=wt$STARS, y=wt$ResidualSugar)) +
    geom_point(shape=1) 

qplot(wt$ResidualSugar,
      binwidth = 1, 
      fill=I("black"))

ggplot(wt, aes(x=wt$TARGET, y=wt$ResidualSugar)) +
    geom_point(shape=1) 

#
ggplot(wt, aes(x=wt$STARS, y=wt$Chlorides)) +
    geom_point(shape=1) 

qplot(wt$Chlorides,
      binwidth = 1, 
      fill=I("black"))

ggplot(wt, aes(x=wt$TARGET, y=wt$Chlorides)) +
    geom_point(shape=1) 


#
ggplot(wt, aes(x=wt$STARS, y=wt$Chlorides)) +
    geom_point(shape=1) 

qplot(wt$Chlorides,
      binwidth = 1, 
      fill=I("black"))

ggplot(wt, aes(x=wt$TARGET, y=wt$Chlorides)) +
    geom_point(shape=1) 

#
ggplot(wt, aes(x=wt$STARS, y=wt$pH)) +
    geom_point(shape=1) 

qplot(wt$pH,
      binwidth = 1, 
      fill=I("black"))

ggplot(wt, aes(x=wt$TARGET, y=wt$pH)) +
    geom_point(shape=1) 

#
ggplot(wt, aes(x=wt$STARS, y=wt$Alcohol)) +
    geom_point(shape=1) 

qplot(wt$Alcohol,
      binwidth = 1, 
      fill=I("black"))

ggplot(wt, aes(x=wt$TARGET, y=wt$Alcohol)) +
    geom_point(shape=1) 

#
ggplot(wt, aes(x=wt$STARS, y=wt$LabelAppeal)) +
    geom_point(shape=1) 

qplot(wt$LabelAppeal,
      binwidth = 1, 
      fill=I("black"))

ggplot(wt, aes(x=wt$TARGET, y=wt$LabelAppeal)) +
    geom_point(shape=1) 

wt$STARS[is.na(wt$STARS)] = 0


Model1 <- glm(wt$TARGET~wt$STARS, family = "poisson")

summary(Model1)

library(AER)

dispersiontest(Model1,trafo=2)

Model2 <- glm(wt$TARGET~wt$FixedAcidity + wt$VolatileAcidity + wt$ResidualSugar + wt$pH, family = "poisson")

summary(Model2)

dispersiontest(Model2,trafo=2)

Model3 <- glm(wt$TARGET~wt$Alcohol, family = "poisson")

summary(Model3)

dispersiontest(Model3,trafo=2)

test<-wine.evaluation.data

predictedsales <-predict(Model1,test,type = "response")

write.table(predictedsales <-ppredict(Model1,test,type = "response"), "testoutcomeswine",sep = ",")


library(MASS)

nbModel2 <- glm.nb(wt$TARGET~wt$FixedAcidity + wt$VolatileAcidity + wt$ResidualSugar + wt$pH)

summary(nbModel2)

dispersiontest(nbModel2,trafo=2)


nbModel3 <- glm.nb(wt$TARGET~wt$Alcohol)

summary(nbModel3)

dispersiontest(nbModel3,trafo=2)







```



